# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QColor
from PyQt5.QtWidgets import QFileDialog, QApplication
from main.paper_test import RegisterHelper

class Ui_Dialog(object):

    def __init__(self):
        # self.source_imagePath = '../datasets/row_data/multispectral/door1.jpg'
        # self.target_imagePath = '../datasets/row_data/multispectral/door1.jpg'
        self.source_imagePath = None
        self.target_imagePath = None
        self.itermax = 800
        self.registerHelper = RegisterHelper()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 525)
        self.selectimg1 = QtWidgets.QPushButton(Dialog)
        # self.selectimg1.setGeometry(QtCore.QRect(50, 130, 75, 23))
        self.selectimg1.setGeometry(QtCore.QRect(50, 150, 95, 43))
        self.selectimg1.setObjectName("selectimg1")
        self.selectimg2 = QtWidgets.QPushButton(Dialog)
        self.selectimg2.setGeometry(QtCore.QRect(260, 150, 95, 43))
        self.selectimg2.setObjectName("selectimg2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 380, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 380, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 380, 54, 12))
        self.label_3.setObjectName("label_3")
        self.showimg1 = QtWidgets.QLabel(Dialog)
        self.showimg1.setGeometry(QtCore.QRect(10, 190, 181, 161))
        self.showimg1.setObjectName("showimg1")
        self.showimg2 = QtWidgets.QLabel(Dialog)
        self.showimg2.setGeometry(QtCore.QRect(200, 190, 181, 161))
        self.showimg2.setObjectName("showimg2")
        self.showimg3 = QtWidgets.QLabel(Dialog)
        self.showimg3.setGeometry(QtCore.QRect(410, 190, 181, 161))
        self.showimg3.setObjectName("showimg3")
        self.registerButton = QtWidgets.QPushButton(Dialog)
        self.registerButton.setGeometry(QtCore.QRect(450, 450, 85, 33))
        self.registerButton.setObjectName("registerButton")

        self.showimg1.setAutoFillBackground(True)
        self.showimg2.setAutoFillBackground(True)
        self.showimg3.setAutoFillBackground(True)
        background_color = QColor()
        background_color.setNamedColor('#FFFFFF')
        palette = QPalette()
        palette.setColor(QPalette.Window, background_color)
        self.showimg1.setPalette(palette)
        self.showimg2.setPalette(palette)
        self.showimg3.setPalette(palette)

        self.selectimg1.clicked.connect(self.openImage1)
        self.selectimg2.clicked.connect(self.openImage2)

        self.registerButton.clicked.connect(self.register)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # self.register()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.selectimg1.setText(_translate("Dialog", "选择待配准图像"))
        self.selectimg2.setText(_translate("Dialog", "选择模板图像"))
        self.label.setText(_translate("Dialog", "source"))
        self.label_2.setText(_translate("Dialog", "target"))
        self.label_3.setText(_translate("Dialog", "warped"))
        self.showimg1.setText(_translate("Dialog", "source"))
        self.showimg2.setText(_translate("Dialog", "target"))
        self.showimg3.setText(_translate("Dialog", "warped"))
        self.registerButton.setText(_translate("Dialog", "register"))

    def openImage1(self):
        imgName, imgType = QFileDialog.getOpenFileName(self, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QtGui.QPixmap(imgName).scaled(self.showimg1.width(), self.showimg1.height())
        self.source_imagePath = imgName
        self.showimg1.setPixmap(jpg)

    def openImage2(self):
        imgName, imgType = QFileDialog.getOpenFileName(self, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QtGui.QPixmap(imgName).scaled(self.showimg2.width(), self.showimg2.height())
        self.target_imagePath = imgName
        self.showimg2.setPixmap(jpg)

    def register(self,type='cnn'):
        '''
        :param type: cnn  |  ntg | cnn_ntg
        :return:
        '''
        print(self.source_imagePath,self.target_imagePath," type:"+type)

        if type == 'cnn':
            image = self.registerHelper.register_CNN(self.source_imagePath,self.target_imagePath)
        elif type == 'ntg':
            image = self.registerHelper.register_NTG(self.source_imagePath,self.target_imagePath,itermax=self.itermax)
        else:
            image = self.registerHelper.register_CNN_NTG(self.source_imagePath,self.target_imagePath,itermax=self.itermax)
        print("配准完成，开始显示图片")
        image = QtGui.QImage(image,image.shape[1],image.shape[0],QtGui.QImage.Format_RGB888)
        print("QImage 完成")
        pix = QtGui.QPixmap(image).scaled(self.showimg3.width(), self.showimg3.height())
        print("填充pix")
        self.showimg3.setPixmap(pix)
        print("显示完成")
        time.sleep(0.5)
        QApplication.notify()
